name: automatic package building by tagging privacyidea repository
on:
  repository_dispatch:
    types: [tag-created]

jobs:
  build-noble:
    name: Ubuntu 24.04 LTS build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build core package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
          ls -l *
          pwd
          cd .. 
          pwd          
          ls -l *
      - name: Collect packages
        run: mkdir -p packages && mv ../*.deb packages/
      - name: Upload built packages
        uses: actions/upload-artifact@v3
        with:
          name: built-packages
          path: packages/*.deb
