name: automatic package building by tagging privacyidea repository
on:
  repository_dispatch:
    types: [tag-created]

jobs:
  build-noble:
    name: Ubuntu 24.04 LTS build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build privacyIDEA package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect core+server packages
        run: mkdir -p packages-core-server && mv *.deb packages-core-server/
      - name: Upload server built packages
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-core-server_noble
          path: packages-core-server/*.deb
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect radius package
        run: mkdir -p package-radius && mv *.deb package-radius/
      - name: Upload radius built package
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-radius_noble
          path: package-radius/*.deb

  build-jammy:
    name: Ubuntu 22.04 LTS build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build privacyIDEA package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect core+server packages
        run: mkdir -p packages-core-server && mv *.deb packages-core-server/
      - name: Upload server built packages
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-core-server_noble
          path: packages-core-server/*.deb
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect radius package
        run: mkdir -p package-radius && mv *.deb package-radius/
      - name: Upload radius built package
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-radius_noble
          path: package-radius/*.deb

  build-focal:
    name: Ubuntu 20.04 LTS build - Tag: ${{ github.event.client_payload.tag }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build privacyIDEA package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect core+server packages
        run: mkdir -p packages-core-server && mv *.deb packages-core-server/
      - name: Upload server built packages
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-core-server_noble
          path: packages-core-server/*.deb
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i "s/trusty/$(lsb_release -cs)/g" privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Collect radius package
        run: mkdir -p package-radius && mv *.deb package-radius/
      - name: Upload radius built package
        uses: actions/upload-artifact@v4
        with:
          name: privacyidea-radius_noble
          path: package-radius/*.deb
