name: Ubuntu
on:
  push:
  release:
    types: [released]

jobs:
  build-jammy:
    name: Ubuntu 22.04 LTS build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build core package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i 's/{{CODENAME}}/jammy/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i 's/{{CODENAME}}/jammy/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i 's/{{CODENAME}}/jammy/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian

  build-focal:
    name: Ubuntu 20.04 LTS build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo add-apt-repository ppa:jyrki-pulliainen/dh-virtualenv
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build privacyID3A package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i 's/{{CODENAME}}/focal/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          cp -r deploy/* privacyidea/deploy
          sed -i 's/{{CODENAME}}/focal/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Build radius packages
        run: |
          mv debian_radius privacyidea/debian
          sed -i 's/{{CODENAME}}/focal/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Setup SSH and transfer
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 39122 -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
          ls *.deb
          for deb_file in *.deb; do
           scp $deb_file -p 39122 -o StrictHostKeyChecking=no -o ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/action/packages/
          done
