name: Ubuntu
on:
  push:
  release:
    types: [released]

jobs:
  build-jammy:
    name: Ubuntu 22.04 LTS build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential debhelper devscripts equivs dh-virtualenv
      - name: Build core package
        env:
          DH_VIRTUALENV_INSTALL_ROOT: /opt
        run: |
          mv debian_privacyidea privacyidea/debian
          sed -i 's/{{CODENAME}}/jammy/g' privacyidea/debian/changelog
          cd privacyidea
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b --source-option=-Sa
          rm -r debian
          cd ..
      - name: Build server packages
        run: |
          mv debian_server privacyidea/debian
          sed -i 's/{{CODENAME}}/jammy/g' debian/changelog
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
      - name: Build radius packages
        run: |
          pwd
          mv debian_radius privacyidea/debian
          ls -la
          sed -i 's/{{CODENAME}}/jammy/g' debian/changelog
          sudo mk-build-deps -ri
          dpkg-buildpackage -us -uc -b
          rm -r debian
